---
title: "Final Project"
author: "Dan Barrett"
date: "11/23/2020"
output: html_document
runtime: shiny
---


Question 6

```{r}
library(tidyverse)
library(shiny)

d <-read_csv('titanic.csv')

variables_names = names(d)

ui <- fluidPage(
  
  titlePanel("Select Plot"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      selectInput(
        inputId ="var1",
        label = "Select a Numeric Variables",
        choices = variables_names, selected = "Age"
      ),
      
      selectInput(
        inputId ="var2",
        label = "Select a Numerical Variables",
        choices = variables_names,
        selected = "Fare"
      ),
      
      radioButtons(inputId = "plot_choice", 
                   label = h3("Select Plot:"),
                   choices = c("Scatter Plot" = "scatter",
                     "Smoothed Plot" = "smooth"),
                   selected = 'scatter')
      
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Histogram ----
      
      plotOutput(outputId = 'show_plot')
    )
  )
)

# server is a function! 
server <- function(input, output) {
  
  
  output$show_plot <- renderPlot({
    
    v1 = input$var1
    v2 = input$var2
   
    
    library(ggplot2)
    
    if(input$plot_choice == 'scatter')
      
    {
      ggplot(d, aes(x = d[[v1]], y = d[[v2]]))+
        geom_point()+
        labs(x = v1, y = v2)
    }
    
    else
    {
      ggplot(d, aes(x = d[[v1]], y = d[[v2]]))+
        geom_smooth()+
        labs(x = v1, y = v2)
    }
      
      
    
  })
  
}
# app
shinyApp(ui = ui, server = server)
```


Question 7


```{r}
library(tidyverse)
library(shiny)

d = read_csv('titanic.csv')

variables_names = names(d)


ui <- fluidPage(
  
  titlePanel("Histogram Plot"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      selectInput(
        inputId ="var1",
        label = "Select a Numeric Variables",
        choices = variables_names, selected = "Age"
      ),
      
      selectInput(
        inputId ="var2",
        label = "Select a Categorical Variables",
        choices = variables_names,
        selected = "Sex"
      ),
      
      checkboxGroupInput(inputId = "Pclass_selection", label = "Select Class of Passenger",
                         choices = names(table(d$Pclass)), inline = TRUE),
      
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Histogram ----
      
      plotOutput(outputId = 'show_plot')
    )
  )
)

# server is a function! 
server <- function(input, output) {
  
  
  output$show_plot <- renderPlot({
    
    v1 = input$var1
    v2 = input$var2
   
    d <- d %>% filter(Pclass %in% input$Pclass_selection)
    
    library(ggplot2)
    
      ggplot(d, aes(x = d[[v1]], fill = as.factor(d[[v2]])))+
        geom_histogram()+
        labs(x = v1, fill = v2)
    
    
  })
  
}
# app
shinyApp(ui = ui, server = server)
```



Question 8


```{r}
library(tidyverse)
library(shiny)

d = read_csv('titanic.csv')

variables_names = names(d)


ui <- fluidPage(
  
  titlePanel("Plot Builder"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      selectInput(
        inputId ="var1",
        label = "Select a Numeric Variables",
        choices = variables_names, selected = "Fare"
      ),

      checkboxGroupInput(inputId = "Pclass_selection", label = "Select Class of Passenger",
                         choices = names(table(d$Pclass)), inline = TRUE),
      
      radioButtons(inputId = "plot_choice", 
             label = h3("Select Plot Type:"),
             choices = c("Density" = "density",
               "Histogram" = "histogram"),
             selected = 'density'),
      
      sliderInput(inputId = "Age",
            "Select Age Range:",
            min = min(d$Age, na.rm=TRUE),
            max = max(d$Age, na.rm=TRUE),
            value= c(15, 60))
      
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Histogram ----
      
      plotOutput(outputId = 'show_plot')
    )
  )
)

# server is a function! 
server <- function(input, output) {
  
  
  output$show_plot <- renderPlot({
    
    v1 = input$var1
   
    d <- d %>% filter(Pclass %in% input$Pclass_selection)
    d <- d %>% filter(Age>input$Age[1], Age<input$Age[2])
    
    library(ggplot2)
    
    if(input$plot_choice == 'density')
      
    {
      ggplot(d, aes(x = d[[v1]]))+
        geom_density()+
        labs(x = v1)
    }
    
    else
    {
      ggplot(d, aes(x = d[[v1]]))+
        geom_histogram()+
        labs(x = v1)
    }
    
  })
  
}
# app
shinyApp(ui = ui, server = server)
```



